window.embeddedUITexts = {
  de: {
    // Buttons
    btnContinue: "Weiter",
    btnStart: "Start",
    btnStop: "Stopp",
    fillRandomBtn: "Rnd",
    resetBtn: "Zurück",
    startPauseBtn: "Start",
    // Labels
    labelDelay: "Verzögerung (ms)",
    labelSpeed: "Tempo",
    uiLangLabel: "Oberfläche:",
    // Tooltips and alerts
    alertInvalidFormat: "Zeit im Format HH:MM eingeben",
    alertInvalidPhrase: "Ungültige Zeit oder keine Phrase verfügbar.",
    fillRandomBtnTitle: "Mit zufälligen Zeiten füllen",
    randomBtnTitle: "Zufällige Zeit generieren",
    resetSettingsTitle: "Auf Standard zurücksetzen",
    resetBtnTitle: "Sequenz zurücksetzen",
    speakBtnTitle: "Aktuelle Zeit abspielen",
    startPauseBtnTitle: "Sequenz starten oder pausieren",
    uiLangSelectTitle: "Oberflächensprache auswählen",
  },
  en: {
    // Buttons
    btnContinue: "Continue",
    btnStart: "Start",
    btnStop: "Stop",
    fillRandomBtn: "Rnd",
    resetBtn: "Reset",
    startPauseBtn: "Start",
    // Labels
    labelDelay: "Delay (ms)",
    labelSpeed: "Speed",
    uiLangLabel: "Interface:",
    // Tooltips and alerts
    alertInvalidFormat: "Enter time in HH:MM format",
    alertInvalidPhrase: "Invalid time or unable to generate phrase.",
    fillRandomBtnTitle: "Fill with random times",
    randomBtnTitle: "Generate random",
    resetSettingsTitle: "Reset to default settings",
    resetBtnTitle: "Reset sequence",
    speakBtnTitle: "Play this time",
    startPauseBtnTitle: "Start or pause sequence",
    uiLangSelectTitle: "Select interface language",
  },
  fr: {
    // Buttons
    btnContinue: "Continuer",
    btnStart: "Démarrer",
    btnStop: "Arrêter",
    fillRandomBtn: "Rnd",
    resetBtn: "Réinit.",
    startPauseBtn: "Démarrer",
    // Labels
    labelDelay: "Délai (ms)",
    labelSpeed: "Vitesse",
    uiLangLabel: "Interface :",
    // Tooltips and alerts
    alertInvalidFormat: "Entrez l’heure au format HH:MM",
    alertInvalidPhrase: "Heure invalide ou phrase indisponible.",
    fillRandomBtnTitle: "Remplir avec des heures aléatoires",
    randomBtnTitle: "Générer aléatoire",
    resetSettingsTitle: "Restaurer les paramètres par défaut",
    resetBtnTitle: "Réinitialiser la séquence",
    speakBtnTitle: "Jouer cette heure",
    startPauseBtnTitle: "Démarrer ou mettre en pause la séquence",
    uiLangSelectTitle: "Choisir la langue de l’interface",
  },
  nl: {
    // Buttons
    btnContinue: "Doorgaan",
    btnStart: "Start",
    btnStop: "Stop",
    fillRandomBtn: "Rnd",
    resetBtn: "Reset",
    startPauseBtn: "Start",
    // Labels
    labelDelay: "Vertraging (ms)",
    labelSpeed: "Snelheid",
    uiLangLabel: "Interface:",
    // Tooltips and alerts
    alertInvalidFormat: "Voer tijd in UU:MM formaat",
    alertInvalidPhrase: "Ongeldige tijd of geen zin beschikbaar.",
    fillRandomBtnTitle: "Vul met willekeurige tijden",
    randomBtnTitle: "Genereer willekeurig",
    resetSettingsTitle: "Herstel naar standaardinstellingen",
    resetBtnTitle: "Reset de reeks",
    speakBtnTitle: "Speel deze tijd af",
    startPauseBtnTitle: "Start of pauzeer de reeks",
    uiLangSelectTitle: "Kies interface taal",
  },
  pl: {
    // Buttons
    btnContinue: "Kontynuuj",
    btnStart: "Start",
    btnStop: "Stop",
    fillRandomBtn: "Rnd",
    resetBtn: "Reset",
    startPauseBtn: "Start",
    // Labels
    labelDelay: "Opóźnienie (ms)",
    labelSpeed: "Prędkość",
    uiLangLabel: "Interfejs:",
    // Tooltips and alerts
    alertInvalidFormat: "Podaj czas w formacie GG:MM",
    alertInvalidPhrase: "Nieprawidłowy czas lub brak frazy.",
    fillRandomBtnTitle: "Wypełnij losowymi czasami",
    randomBtnTitle: "Wygeneruj losowo",
    resetSettingsTitle: "Przywróć ustawienia domyślne",
    resetBtnTitle: "Zresetuj sekwencję",
    speakBtnTitle: "Odtwórz ten czas",
    startPauseBtnTitle: "Uruchom lub zatrzymaj sekwencję",
    uiLangSelectTitle: "Wybierz język interfejsu",
  },
  pt: {
    // Buttons
    btnContinue: "Continuar",
    btnStart: "Iniciar",
    btnStop: "Parar",
    fillRandomBtn: "Rnd",
    resetBtn: "Redef.",
    startPauseBtn: "Iniciar",
    // Labels
    labelDelay: "Atraso (ms)",
    labelSpeed: "Velocidade",
    uiLangLabel: "Interface:",
    // Tooltips and alerts
    alertInvalidFormat: "Digite a hora no formato HH:MM",
    alertInvalidPhrase: "Hora inválida ou frase indisponível.",
    fillRandomBtnTitle: "Preencher com horas aleatórias",
    randomBtnTitle: "Gerar aleatório",
    resetSettingsTitle: "Restaurar configurações padrão",
    resetBtnTitle: "Redefinir sequência",
    speakBtnTitle: "Tocar esta hora",
    startPauseBtnTitle: "Iniciar ou pausar sequência",
    uiLangSelectTitle: "Selecione o idioma da interface",
  },
  ru: {
    // Buttons
    btnContinue: "Дальше",
    btnStart: "Старт",
    btnStop: "Стоп",
    fillRandomBtn: "Rnd",
    resetBtn: "Сброс",
    startPauseBtn: "Старт",
    // Labels
    labelDelay: "Пауза (мс)",
    labelSpeed: "Скорость",
    uiLangLabel: "Интерфейс:",
    // Tooltips and alerts
    alertInvalidFormat: "Введите время в формате ЧЧ:ММ",
    alertInvalidPhrase: "Нет фразы для этого времени.",
    fillRandomBtnTitle: "Заполнить случайными временами",
    randomBtnTitle: "Генерировать случайное",
    resetSettingsTitle: "Сбросить настройки по умолчанию",
    resetBtnTitle: "Сбросить последовательность",
    speakBtnTitle: "Воспроизвести это время",
    startPauseBtnTitle: "Запустить или приостановить последовательность",
    uiLangSelectTitle: "Выберите язык интерфейса",
  },
  tr: {
    // Buttons
    btnContinue: "Devam",
    btnStart: "Başla",
    btnStop: "Dur",
    fillRandomBtn: "Rnd",
    resetBtn: "Sıfırla",
    startPauseBtn: "Başla",
    // Labels
    labelDelay: "Gecikme (ms)",
    labelSpeed: "Hız",
    uiLangLabel: "Arayüz:",
    // Tooltips and alerts
    alertInvalidFormat: "SS:DD formatında saat girin",
    alertInvalidPhrase: "Geçersiz saat veya cümle.",
    fillRandomBtnTitle: "Rastgele zamanlarla doldur",
    randomBtnTitle: "Rastgele oluştur",
    resetSettingsTitle: "Varsayılan ayarları sıfırla",
    resetBtnTitle: "Sıralamayı sıfırla",
    speakBtnTitle: "Bu zamanı çal",
    startPauseBtnTitle: "Sıralamayı başlat veya duraklat",
    uiLangSelectTitle: "Arayüz dili seçin",
  },
  uk: {
    // Buttons
    btnContinue: "Далі",
    btnStart: "Старт",
    btnStop: "Стоп",
    fillRandomBtn: "Rnd",
    resetBtn: "Скинути",
    startPauseBtn: "Старт",
    // Labels
    labelDelay: "Затримка (мс)",
    labelSpeed: "Швидкість",
    uiLangLabel: "Інтерфейс:",
    // Tooltips and alerts
    alertInvalidFormat: "Введіть час у форматі ГГ:ХХ",
    alertInvalidPhrase: "Немає фрази для цього часу.",
    fillRandomBtnTitle: "Заповнити випадковим часом",
    randomBtnTitle: "Згенерувати випадкове",
    resetSettingsTitle: "Скинути до налаштувань за замовчуванням",
    resetBtnTitle: "Скинути послідовність",
    speakBtnTitle: "Відтворити цей час",
    startPauseBtnTitle: "Запустити або призупинити послідовність",
    uiLangSelectTitle: "Оберіть мову інтерфейсу",
  },
};
