// ui_CLT_texts.js

window.embeddedUITexts = {
  en: {
    uiLangLabel: "Interface",
    startPauseBtn: "Start",
    stop: "Stop",
    continue: "Continue",
    resetBtn: "Reset",
    resetSettings: "Reset Settings",
    fillRandom: "Fill Random",
    invalidTime: "Enter time in HH:MM format",
    noPhrase: "Invalid time or unable to generate phrase.",
    labelSpeed: "Speed",
    labelDelay: "Delay",
  },
  de: {
    uiLangLabel: "Interface",
    startPauseBtn: "Starten",
    stop: "Stopp",
    continue: "Fortsetzen",
    resetBtn: "Zurücksetzen",
    resetSettings: "Einstellungen zurücksetzen",
    fillRandom: "Zufällig füllen",
    invalidTime: "Zeit im HH:MM-Format eingeben",
    noPhrase: "Ungültige Zeit oder Ausdruck konnte nicht erzeugt werden.",
    labelSpeed: "Geschwindigkeit",
    labelDelay: "Verzögerung",
  },
  fr: {
    uiLangLabel: "Interface",
    startPauseBtn: "Démarrer",
    stop: "Arrêter",
    continue: "Continuer",
    resetBtn: "Réinitialiser",
    resetSettings: "Réinitialiser les paramètres",
    fillRandom: "Remplir au hasard",
    invalidTime: "Entrez l'heure au format HH:MM",
    noPhrase: "Heure invalide ou impossible de générer la phrase.",
    labelSpeed: "Vitesse",
    labelDelay: "Délai",
  },
  nl: {
    uiLangLabel: "Interface",
    startPauseBtn: "Start",
    stop: "Stop",
    continue: "Doorgaan",
    resetBtn: "Resetten",
    resetSettings: "Instellingen resetten",
    fillRandom: "Willekeurig invullen",
    invalidTime: "Voer tijd in HH:MM formaat in",
    noPhrase: "Ongeldige tijd of kon geen zin genereren.",
    labelSpeed: "Snelheid",
    labelDelay: "Vertraging",
  },
  pl: {
    uiLangLabel: "Interfejs",
    startPauseBtn: "Start",
    stop: "Stop",
    continue: "Kontynuuj",
    resetBtn: "Zresetuj",
    resetSettings: "Zresetuj ustawienia",
    fillRandom: "Wypełnij losowo",
    invalidTime: "Wprowadź czas w formacie HH:MM",
    noPhrase: "Nieprawidłowy czas lub brak możliwości wygenerowania zwrotu.",
    labelSpeed: "Szybkość",
    labelDelay: "Opóźnienie",
  },
  pt: {
    uiLangLabel: "Interface",
    startPauseBtn: "Iniciar",
    stop: "Parar",
    continue: "Continuar",
    resetBtn: "Redefinir",
    resetSettings: "Redefinir configurações",
    fillRandom: "Preencher aleatoriamente",
    invalidTime: "Insira o horário no formato HH:MM",
    noPhrase: "Horário inválido ou não foi possível gerar frase.",
    labelSpeed: "Velocidade",
    labelDelay: "Atraso",
  },
  ru: {
    uiLangLabel: "Интерфейс",
    startPauseBtn: "Старт",
    stop: "Стоп",
    continue: "Продолжить",
    resetBtn: "Сброс",
    resetSettings: "Сбросить настройки",
    fillRandom: "Заполнить случайно",
    invalidTime: "Введите время в формате ЧЧ:ММ",
    noPhrase: "Неверное время или не удалось сформулировать фразу.",
    labelSpeed: "Скорость",
    labelDelay: "Задержка",
  },
  tr: {
    uiLangLabel: "Arayüz",
    startPauseBtn: "Başlat",
    stop: "Durdur",
    continue: "Devam et",
    resetBtn: "Sıfırla",
    resetSettings: "Ayarları sıfırla",
    fillRandom: "Rastgele doldur",
    invalidTime: "Zamanı SS:DD formatında girin",
    noPhrase: "Geçersiz zaman veya cümle oluşturulamadı.",
    labelSpeed: "Hız",
    labelDelay: "Gecikme",
  },
  uk: {
    uiLangLabel: "Інтерфейс",
    startPauseBtn: "Старт",
    stop: "Стоп",
    continue: "Продовжити",
    resetBtn: "Скинути",
    resetSettings: "Скинути налаштування",
    fillRandom: "Заповнити випадково",
    invalidTime: "Введіть час у форматі ГГ:ХХ",
    noPhrase: "Неправильний час або не вдалося згенерувати фразу.",
    labelSpeed: "Швидкість",
    labelDelay: "Затримка",
  },
};
